name: health_tracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.1.4
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.3

  shared_preferences: ^2.0.13
  image_picker: ^1.0.0
  curved_navigation_bar: ^1.0.3
  path_provider: ^2.0.11
  provider: ^6.0.2

  font_awesome_flutter: ^10.1.0

  http: ^1.1.0
  tab_indicator_styler: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_native_splash: ^2.1.1
  date_picker_timeline: ^1.2.3
  table_calendar: ^3.0.5
  animate_do: ^4.0.0
  sizer: ^3.0.5
  equatable: ^2.0.3
  bloc: ^9.0.0
  connectivity_plus: ^6.1.3
  another_flushbar: ^1.10.28
  flutter_bloc: ^9.0.0
  pedometer: ^4.0.1
  intl: ^0.19.0
  fl_chart: ^0.70.2
  percent_indicator: ^4.0.0
  heart_bpm: ^2.0.0+0
  camera: ^0.10.6

  flutter_speed_dial: ^7.0.0
  fab_circular_menu: ^1.0.2
  uuid: ^4.5.1
  #flutter_barcode_scanner: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  numberpicker: ^2.1.1
  pie_chart: ^5.3.1
  introduction_screen: ^3.0.2
  carousel_slider: ^5.0.0
  flutter_spinkit: ^5.1.0
  internet_connection_checker: 0.0.1+4
  flutter_local_notifications: ^18.0.1
  time_range_picker: ^2.1.0
  horizontal_picker: ^1.2.0
  firebase_messaging: ^15.2.2
  expandable_text: ^2.3.0

# dependency_overrides:
  # image_picker_android: 0.8.4+13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/svgs/
    - assets/json/
    - assets/illustrations/

  fonts:
    - family: IndieFlower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Book.otf
